data_params:
    n_samples: 1000
    noise_level: 0.1
    sampling_rate: 100
processing_params:
    smoothing_sigma: 2.0
    filter_cutoff: 0.5
analysis_params:
    significance_level: 0.05
    bootstrap_iterations: 1000
