data_params:
    n_samples: 5000
    noise_level: 0.05
    sampling_rate: 1000
processing_params:
    smoothing_sigma: 1.0
    filter_cutoff: 0.1
analysis_params:
    significance_level: 0.01
    bootstrap_iterations: 5000
