# Timestamp: "2025-10-13 09:05:00 (ywatanabe)"
# File: ./src/scitex/scholar/config/categories/api_keys.yaml
# API keys and credentials configuration

# ----------------------------------------
# Search Engine API Keys
# ----------------------------------------
semantic_scholar_api_key: ${SCITEX_SCHOLAR_SEMANTIC_SCHOLAR_API_KEY:-null}
crossref_api_key: ${SCITEX_SCHOLAR_CROSSREF_API_KEY:-null}
pubmed_api_key: ${SCITEX_SCHOLAR_PUBMED_API_KEY:-null}
twocaptcha_api_key: ${SCITEX_SCHOLAR_2CAPTCHA_API_KEY:-null}

# ----------------------------------------
# Search Engine Credentials
# ----------------------------------------
pubmed_email: ${SCITEX_SCHOLAR_PUBMED_EMAIL:-null}
crossref_email: ${SCITEX_SCHOLAR_CROSSREF_EMAIL:-null}

# EOF
