# Timestamp: "2025-10-13 09:05:00 (ywatanabe)"
# File: ./src/scitex/scholar/config/categories/auth_gateway.yaml
# Authentication gateway configuration for paywalled publishers

# ----------------------------------------
# Active Authentication Provider
# ----------------------------------------
auth_active_provider: openathens

# ----------------------------------------
# Authentication Endpoint Patterns
# ----------------------------------------
# These are intermediate endpoints that perform client-side redirects
auth_endpoint_patterns:
  # OpenAthens
  - "go.openathens.net"
  - "login.openathens.net"
  # Elsevier
  - "auth.elsevier.com"
  - "login.elsevier.com"
  - "secure.jbs.elsevierhealth.com"
  # Nature
  - "idp.nature.com"
  # Generic SSO patterns
  - "shibboleth"
  - "saml"
  - "/ShibAuth/"
  - "/authenticate"
  - "/login"
  - "/signin"
  - "/sso/"

# ----------------------------------------
# Article URL Indicators
# ----------------------------------------
# Patterns for detecting final article destination
article_url_patterns:
  - "/science/article/"
  - "/articles/"
  - "/content/"
  - "/full/"
  - "/fulltext/"
  - "/doi/full/"
  - "/doi/abs/"
  - "/doi/pdf/"
  - ".pdf"

# ----------------------------------------
# Paywalled Publishers
# ----------------------------------------
# Publishers requiring authentication (paywalled content)
# Gateway will visit OpenURL to establish publisher-specific session cookies
paywalled_publishers:
  - name: IEEE
    doi_prefixes:
      - "10.1109"
    domain_patterns:
      - "ieeexplore.ieee.org"
      - "ieee.org"
    preferred_provider: openathens

  - name: Springer
    doi_prefixes:
      - "10.1007"
    domain_patterns:
      - "link.springer.com"
      - "springer.com"
      - "springernature.com"
    preferred_provider: openathens

  - name: Wiley
    doi_prefixes:
      - "10.1002"
      - "10.1111"
    domain_patterns:
      - "onlinelibrary.wiley.com"
      - "wiley.com"
    preferred_provider: openathens

  - name: Nature
    doi_prefixes:
      - "10.1038"
    domain_patterns:
      - "nature.com"
      - "springernature.com"
    preferred_provider: openathens

  - name: ScienceDirect
    doi_prefixes:
      - "10.1016"
    domain_patterns:
      - "sciencedirect.com"
      - "elsevier.com"
    preferred_provider: openathens

  - name: Taylor & Francis
    domain_patterns:
      - "tandfonline.com"
      - "taylorfrancis.com"
    preferred_provider: openathens

  - name: Oxford University Press
    domain_patterns:
      - "academic.oup.com"
      - "oup.com"
    preferred_provider: openathens

  - name: Cambridge University Press
    domain_patterns:
      - "cambridge.org"
    preferred_provider: openathens

  - name: SAGE
    domain_patterns:
      - "journals.sagepub.com"
      - "sagepub.com"
    preferred_provider: openathens

  - name: ACS Publications
    domain_patterns:
      - "pubs.acs.org"
      - "acs.org"
    preferred_provider: openathens

  - name: IOP Publishing
    doi_prefixes:
      - "10.1088"
    domain_patterns:
      - "iopscience.iop.org"
      - "iop.org"
    preferred_provider: openathens

  - name: SSRN
    doi_prefixes:
      - "10.2139"
    domain_patterns:
      - "ssrn.com"
      - "papers.ssrn.com"
    preferred_provider: openathens

  - name: Lancet
    doi_prefixes:
      - "10.1016"
    domain_patterns:
      - "thelancet.com"
      - "lancet.com"
    preferred_provider: openathens

# EOF
