# Timestamp: "2025-10-13 09:05:00 (ywatanabe)"
# File: ./src/scitex/scholar/config/categories/authentication.yaml
# Authentication configuration

# ----------------------------------------
# Authentication Providers
# ----------------------------------------
openathens_enabled: ${SCITEX_SCHOLAR_OPENATHENS_ENABLED:-true}
openathens_email: ${SCITEX_SCHOLAR_OPENATHENS_EMAIL:-null}
ezproxy_email: ${SCITEX_SCHOLAR_EZPROXY_EMAIL:-null}
shibboleth_email: ${SCITEX_SCHOLAR_SHIBBOLETH_EMAIL:-null}

# ----------------------------------------
# SSO Credentials
# ----------------------------------------
sso_username: ${SCITEX_SCHOLAR_SSO_USERNAME:-null}
sso_password: ${SCITEX_SCHOLAR_SSO_PASSWORD:-null}

# ----------------------------------------
# OpenURL Resolver
# ----------------------------------------
openurl_resolver_url: ${SCITEX_SCHOLAR_OPENURL_RESOLVER_URL:-null}

# EOF
