# Timestamp: "2025-10-13 09:05:00 (ywatanabe)"
# File: ./src/scitex/scholar/config/categories/browser.yaml
# Browser and screenshot configuration

# ----------------------------------------
# Browser Settings
# ----------------------------------------
chrome_profile_name: ${SCITEX_SCHOLAR_CHROME_PROFILE_NAME:-null}

# ----------------------------------------
# Screenshot Settings
# ----------------------------------------
capture_screenshots: ${SCITEX_SCHOLAR_CAPTURE_SCREENSHOTS:-true}

# ----------------------------------------
# Unwanted Pages (Auto-close)
# ----------------------------------------
unwanted_pages_expressions:
  - "chrome-extension://"
  - "pbapi.xyz"
  - "options.html"
  - "newtab"

# EOF
