# Timestamp: "2025-10-13 09:05:00 (ywatanabe)"
# File: ./src/scitex/scholar/config/categories/core.yaml
# Core Scholar configuration

# ----------------------------------------
# Paths and Projects
# ----------------------------------------
scholar_dir: ${SCITEX_DIR:-"~/.scitex"}
project: ${SCITEX_SCHOLAR_PROJECT:-"MASTER"}

# ----------------------------------------
# Feature Flags
# ----------------------------------------
debug_mode: ${SCITEX_SCHOLAR_DEBUG_MODE:-false}
enable_auto_enrich: ${SCITEX_SCHOLAR_AUTO_ENRICH:-true}
enable_auto_download: ${SCITEX_SCHOLAR_AUTO_DOWNLOAD:-false}

# ----------------------------------------
# General Settings
# ----------------------------------------
max_workers: 4
verify_ssl: true

# EOF
