# Timestamp: "2025-10-13 09:05:00 (ywatanabe)"
# File: ./src/scitex/scholar/config/categories/doi_publishers.yaml
# DOI prefix to publisher domain mapping

# ----------------------------------------
# DOI to Domain Mapping
# ----------------------------------------
doi_to_domain:
  "10.1038":
    - "nature.com"
    - "springernature.com"
  "10.1016":
    - "sciencedirect.com"
    - "elsevier.com"
  "10.1002":
    - "wiley.com"
    - "onlinelibrary.wiley.com"
  "10.1007":
    - "springer.com"
    - "link.springer.com"
  "10.1126":
    - "science.org"
    - "sciencemag.org"
  "10.1021":
    - "acs.org"
    - "pubs.acs.org"
  "10.1111":
    - "wiley.com"
    - "onlinelibrary.wiley.com"
  "10.1080":
    - "tandfonline.com"
  "10.1177":
    - "sagepub.com"
    - "journals.sagepub.com"
  "10.1093":
    - "oup.com"
    - "academic.oup.com"
  "10.1109":
    - "ieee.org"
    - "ieeexplore.ieee.org"
  "10.1371":
    - "plos.org"
    - "journals.plos.org"
  "10.1073":
    - "pnas.org"
  "10.1136":
    - "bmj.com"
  "10.3389":
    - "frontiersin.org"
  "10.3390":
    - "mdpi.com"

# EOF
