# Timestamp: "2025-10-13 09:05:00 (ywatanabe)"
# File: ./src/scitex/scholar/config/categories/notifications.yaml
# Notification configuration

# ----------------------------------------
# Notification Settings
# ----------------------------------------
notification_email: ${UNIMELB_EMAIL:-null}
notification_from_email: ${SCITEX_EMAIL_AGENT:-"agent@scitex.ai"}

# EOF
