# Timestamp: "2025-10-13 09:37:37 (ywatanabe)"
# File: ./src/scitex/scholar/config/categories/pdf_download.yaml
# PDF download configuration

# ----------------------------------------
# Download Settings
# ----------------------------------------
max_parallel: ${SCITEX_SCHOLAR_PDF_MAX_PARALLEL:-8}
use_parallel: ${SCITEX_SCHOLAR_PDF_USE_PARALLEL:-true}
delay_between_starts: 0.1
default_delay: 10
retry_attempts: 3
timeout: 60

# EOF