# Timestamp: "2025-10-13 09:05:00 (ywatanabe)"
# File: ./src/scitex/scholar/config/categories/publishers_pdf_rules.yaml
# Publisher-specific PDF extraction rules

# ----------------------------------------
# Publisher-Specific PDF Extraction Rules
# ----------------------------------------
publisher_pdf_rules:
  sciencedirect:
    domain_patterns:
      - "sciencedirect.com"
      - "cell.com"
      - "elsevier.com"
    deny_selectors:
      - 'a[href*="/mmc"]'
      - 'a[href*="supplementary"]'
      - 'a[href*="figure"]'
      - 'a[href*="image"]'
      - 'a[href*="thumb"]'
      - 'a[href*="gr1"]'
      - 'a[href*="gr2"]'
      - 'a[href*="gr3"]'
      - 'a[href*="fx1"]'
      - 'a[href*="mmcr"]'
      - '.recommended-articles a'
      - '.related-articles a'
      - '.reference-list a'
      - '.js-related-article a'
      - '[data-track*="related"]'
      - '[data-track*="recommend"]'
    deny_classes:
      - "thumbnail"
      - "figure-download"
      - "supplementary-material"
      - "related-article-link"
      - "reference-link"
      - "recommended-link"
      - "ppt-download"
      - "xls-download"
    deny_text_patterns:
      - "supplementary"
      - "supporting"
      - "figure"
      - "table"
      - "image"
      - "cited by"
      - "related articles"
      - "recommended articles"
      - "download all"
      - "download zip"
      - "powerpoint"
      - "excel"
      - "video"
      - "audio"
    allowed_pdf_patterns:
      - "/pdfft\\?"
      - "/piis.*\\.pdf"
      - "/science/article/pii.*\\.pdf"
    download_selectors:
      - 'a[aria-label="Download PDF"]'
      - 'a.download-pdf-link:not([href*="supplementary"])'
      - 'button.pdf-download'
      - 'a[data-track-action="download pdf"]:not([href*="mmc"])'

  nature:
    domain_patterns:
      - "nature.com"
    deny_selectors:
      - 'a[href*="figures"]'
      - 'a[href*="tables"]'
      - 'a[href*="extended"]'
      - '.c-article-references a'
    deny_classes:
      - "figure-link"
      - "table-link"
      - "supplementary-link"
    deny_text_patterns:
      - "extended data"
      - "supplementary"
      - "source data"
    allowed_pdf_patterns:
      - "\\.pdf$"
      - "/pdf/"
    download_selectors:
      - 'a[data-track-action="download pdf"]'
      - 'a.c-pdf-download__link'

  wiley:
    domain_patterns:
      - "onlinelibrary.wiley.com"
    deny_selectors:
      - 'a[href*="supporting"]'
      - 'a[href*="appendix"]'
      - '.article-references a'
    deny_classes:
      - "supporting-info"
      - "appendix-link"
    deny_text_patterns:
      - "supporting information"
      - "appendix"
    allowed_pdf_patterns:
      - "/epdf/"
      - "/pdf/"
      - "\\.pdf$"
    download_selectors:
      - 'a[title*="PDF"]'
      - 'a.pdf-link'

  springer:
    domain_patterns:
      - "link.springer.com"
      - "springerlink.com"
    deny_selectors:
      - 'a[href*="supplementary"]'
      - 'a[href*="figures"]'
      - '.c-article-references a'
    deny_classes:
      - "supplementary-material"
      - "figure-link"
    deny_text_patterns:
      - "supplementary"
      - "additional file"
    allowed_pdf_patterns:
      - "\\.pdf$"
      - "/content/pdf/"
    download_selectors:
      - 'a.c-pdf-download-link'
      - 'a[data-track-action="download pdf"]'

  ieee:
    domain_patterns:
      - "ieeexplore.ieee.org"
    deny_selectors:
      - 'a[href*="multimedia"]'
      - 'a[href*="stamp"]'
    deny_classes:
      - "stats-document-abstract-multimedia"
    deny_text_patterns:
      - "multimedia"
      - "view document"
    allowed_pdf_patterns:
      - "/iel\\d+/"
      - "\\.pdf$"
    download_selectors:
      - 'a.pdf-btn-link'
      - 'xpl-pdf-btn-link'

  frontiers:
    domain_patterns:
      - "frontiersin.org"
    deny_selectors:
      - 'a[href*="supplementary"]'
      - 'a[href*="datasheet"]'
    deny_classes:
      - "supplementary-material"
    deny_text_patterns:
      - "supplementary"
      - "data sheet"
    allowed_pdf_patterns:
      - "/pdf/"
      - "\\.pdf$"
    download_selectors:
      - 'a.download-files-pdf'
      - 'a[href*="/pdf/"]'

  plos:
    domain_patterns:
      - "plos.org"
      - "plosone.org"
    deny_selectors:
      - 'a[href*="supplementary"]'
      - 'a[href*="figure"]'
    deny_classes:
      - "supplementary"
    deny_text_patterns:
      - "supporting information"
    allowed_pdf_patterns:
      - "\\.pdf$"
      - "/plosone/article/file"
    download_selectors:
      - 'a#downloadPdf'
      - 'a[id="downloadPdf"]'

# EOF
