# Timestamp: "2025-10-13 09:05:00 (ywatanabe)"
# File: ./src/scitex/scholar/config/categories/search_engines.yaml
# Search engine configuration

# ----------------------------------------
# Search Engines Priority Order
# ----------------------------------------
engines:
  - URL
  - CrossRefLocal
  - Semantic_Scholar
  - CrossRef
  - OpenAlex
  - PubMed
  - arXiv

# ----------------------------------------
# Search Settings
# ----------------------------------------
default_search_limit: 20

# EOF
