# Timestamp: "2025-10-13 09:05:00 (ywatanabe)"
# File: ./src/scitex/scholar/config/categories/url_finder_selectors.yaml
# URL finder selectors and patterns

# ----------------------------------------
# Text Patterns for PDF Links
# ----------------------------------------
text_patterns:
  # Common patterns
  - "View full text"
  - "Full Text from Publisher"
  - "Get full text"
  - "Access full text"
  - "Go to article"
  - "Access article"
  # Generic but reliable
  - "Full Text"
  - "Full text"
  - "Article"
  - "View"
  - "PDF"
  - "Download"
  - "GO"

# ----------------------------------------
# Negative Keywords (Filter Out)
# ----------------------------------------
negative_keywords:
  - "cookie"
  - "policy"
  - "about us"
  - "privacy"
  - "terms"
  - "abstract"
  - "preview"
  - "summary"
  - "citation"
  - "cite this"
  - "request"
  - "interlibrary"
  - "inter library"
  - "loan"

# ----------------------------------------
# PDF Download Selectors
# ----------------------------------------
download_selectors:
  # Generic download patterns
  - 'a[data-track-action*="download"]'
  - 'button[data-track-action*="download"]'
  - 'a:has-text("Download PDF")'
  - 'button:has-text("Download PDF")'
  - 'a[download][href*="pdf"]'
  - '.pdf-download-btn'
  - 'a[href*="/pdf/"]'
  - 'a[href*="/doi/pdf/"]'
  - 'a[href*="type=printable"]'

  # Publisher-specific selectors
  # ScienceDirect (Elsevier)
  - 'a.PdfLink'
  - 'a.article-tools-pdf-link'

  # Wiley Online Library
  - 'a#article-pdf-link'
  - 'a.pdf-download'

  # SpringerLink
  - 'a[data-track-action="download pdf"]'
  - 'a.c-pdf-download__link'

  # Oxford Academic
  - 'a.al-link.pdf-link'

# ----------------------------------------
# Dropdown Selectors
# ----------------------------------------
dropdown_selectors:
  - 'button:has-text("Download")'
  - '.dropdown-toggle:has-text("Download")'
  - '[data-toggle="dropdown"]:has-text("Download")'
  - ".download-dropdown"
  - 'button[aria-label*="Download"]'

# ----------------------------------------
# Supplementary Material Selectors
# ----------------------------------------
supplementary_selectors:
  - 'a[href*="supplementary"]'
  - 'a[href*="supplement"]'
  - 'a[href*="additional"]'
  - 'a[href*="supporting"]'
  - 'a[href*="SI"]'
  - 'a[href*="ESM"]'

# ----------------------------------------
# PDF View Selectors
# ----------------------------------------
pdf_view_selectors:
  - 'a:has-text("View PDF")'
  - 'a:has-text("PDF")'
  - "a.pdf-link"
  - 'a[href*="/pdf/"]'
  - 'button:has-text("PDF")'
  - 'a#ViewPDF'
  - 'div#accessbar a'

# ----------------------------------------
# Deny Selectors (Elements to Skip)
# ----------------------------------------
deny_selectors:
  # Navigation and UI elements
  - 'aside *'
  - '.sidebar *'
  - '.navigation *'
  - '.footer *'
  - '.header *'
  # Recommendation sections
  - '.recommended *'
  - '.related-articles *'
  - '.you-may-also-like *'
  # Social and sharing
  - '.social-share *'
  - '.share-buttons *'
  # Issue/Volume downloads (not single article)
  - 'a:has-text("Download Issue")'
  - 'a:has-text("Download Volume")'
  - 'a:has-text("Full Issue")'

deny_classes:
  - "recommended"
  - "sidebar"
  - "footer-content"
  - "social-share"
  - "issue-download"
  - "volume-download"

deny_text_patterns:
  - "Download Issue"
  - "Download Volume"
  - "Full Issue"
  - "Complete Issue"
  - "Entire Issue"
  - "Subscribe"
  - "Sign up"

# EOF
