# Timestamp: "2025-10-13 09:05:00 (ywatanabe)"
# File: ./src/scitex/scholar/config/categories/url_finder_openurl.yaml
# OpenURL resolver patterns for finding PDFs

# ----------------------------------------
# OpenURL Available From Patterns
# ----------------------------------------
# High priority patterns for OpenURL resolvers
openurl_available_from_patterns:
  # University of Melbourne specific patterns (based on screenshot)
  # Put these first since they are most specific to your use case
  - "Available from American Association for the Advancement of Science"
  - "Available from JSTOR Archival Journals and Primary Sources Collection"
  - "Available from JSTOR Health & General Sciences"
  - "Available from PubMed Central"
  - "Available from American Physiological Society Paid"

  # Publisher-specific patterns (most reliable)
  - "Available from Nature"
  - "Available from Nature Publishing Group"
  - "Available from ScienceDirect"
  - "Available from Elsevier"
  - "Available from Wiley"
  - "Available from Wiley Online Library"
  - "Available from Springer"
  - "Available from SpringerLink"
  - "Available from Taylor & Francis"
  - "Available from SAGE"
  - "Available from SAGE Publications"
  - "Available from Oxford"
  - "Available from Oxford Academic"
  - "Available from IEEE"
  - "Available from IEEE Xplore"
  - "Available from PLOS"
  - "Available from PLOS ONE"
  - "Available from BMJ"
  - "Available from Frontiers"
  - "Available from MDPI"
  - "Available from American Chemical Society"
  - "Available from ACS"
  - "Available from ACS Publications"
  - "Available from PNAS"
  - "Available from Science"
  - "Available from AAAS"
  - "Available from IEEE"
  - "Available from Institute of Physics"
  - "Available from Unpaywall"
  - "Available from Open Access"

# ----------------------------------------
# Resolver Link Selectors (Priority Order)
# ----------------------------------------
structure_selectors:
  # University of Melbourne specific (based on screenshots)
  - 'tr:has-text("Available from") a:has-text("GO")'
  - 'td a[href*="javascript:openSFXMenuLink"]:has-text("GO")'
  - 'a[title="Navigate to target in new window"]'

  # SFX (ExLibris) - used by many universities
  - "div#fulltext a"
  - "div.sfx-fulltext a"
  - "div.results-title > a"
  - "td.object-cell a"
  - ".getFullTxt a"
  - 'div[id*="fulltext"] a'
  - 'div[class*="fulltext"] a'

  # Primo (ExLibris)
  - "prm-full-view-service-container a"
  - "span.availability-status-available a"

  # Summon (ProQuest)
  - ".summon-fulltext-link"
  - "a.summon-link"

  # EDS (EBSCO)
  - "a.fulltext-link"
  - ".ft-link a"

  # Generic patterns
  - "a.full-text-link"
  - "a.fulltext"
  - "a#full-text-link"
  - ".access-link a"
  - ".available-link a"

# EOF
