# Timestamp: "2025-06-14 22:18:00 (ywatanabe)"
# File: .github/workflows/install-develop-branch.yml

name: install-develop-branch

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: install-develop-branch
      run: |
          python -m pip install -U pip
          pip install git+https://github.com/ywatanabe1989/SciTeX-Code.git@develop
          python ./tests/custom/test_scitex_run.py

# EOF