ID: 2025Y-07M-22D-15h21m33s_hm0H
PID: 144881
START_TIME: 2025-07-22 15:21:33.988427
FILE: ./src/scitex/scholar/examples/example.py
SDIR: 
    /home/ywatanabe/proj/SciTeX-Code/src/scitex/scholar/examples/example_out/RUNNING/2025Y-07M-22D-15h21m33s_hm0H/
REL_SDIR: src/scitex/scholar/examples/example_out/
ARGS:
    query: epilepsy prediction
    limit: 50
    sources:
        - pubmed
    year_min: 2020
    year_max: 2024
    display_count: 3
    save: true
EXIT_STATUS: 0
END_TIME: 2025-07-22 15:22:34.015068
RUN_TIME: 00:01:00
