ID: 2025Y-07M-22D-15h19m09s_M7p7
PID: 144258
START_TIME: 2025-07-22 15:19:09.106640
FILE: ./src/scitex/scholar/examples/example.py
SDIR: 
    /home/ywatanabe/proj/SciTeX-Code/src/scitex/scholar/examples/example_out/RUNNING/2025Y-07M-22D-15h19m09s_M7p7/
REL_SDIR: src/scitex/scholar/examples/example_out/
ARGS:
    query: epilepsy prediction
    limit: 50
    sources:
        - pubmed
    year_min: 2020
    year_max: 2024
    display_count: 3
    save: false
EXIT_STATUS: 0
END_TIME: 2025-07-22 15:20:08.409125
RUN_TIME: 00:00:59
