# Timestamp: "2025-07-31 00:49:10 (ywatanabe)"
# File: ./src/scitex/scholar/config/default_config.yaml
# SciTeX Scholar Default Configuration
# This file shows all available configuration options with their default values.

# ============================================================================
# API AUTHENTICATION
# ============================================================================

# Semantic Scholar API key
semantic_scholar_api_key: ${SCITEX_SCHOLAR_SEMANTIC_SCHOLAR_API_KEY:-null}

# CrossRef API key
crossref_api_key: ${SCITEX_SCHOLAR_CROSSREF_API_KEY:-null}

# Email for PubMed API access
pubmed_email: ${SCITEX_SCHOLAR_PUBMED_EMAIL:-"research@example.com"}

# Email for CrossRef API access
crossref_email: ${SCITEX_SCHOLAR_CROSSREF_EMAIL:-"research@example.com"}

# ============================================================================
# FEATURE SETTINGS
# ============================================================================

# Automatically enrich papers with impact factors and citation counts
enable_auto_enrich: ${SCITEX_SCHOLAR_AUTO_ENRICH:-true}

# Use impact_factor package for journal metrics
use_impact_factor_package: ${SCITEX_SCHOLAR_USE_IMPACT_FACTOR_PACKAGE:-true}

# Automatically download open-access PDFs during search
enable_auto_download: ${SCITEX_SCHOLAR_AUTO_DOWNLOAD:-false}

# ============================================================================
# OPENATHENS AUTHENTICATION
# ============================================================================

# Enable OpenAthens authentication
openathens_enabled: ${SCITEX_SCHOLAR_OPENATHENS_ENABLED:-false}

# OpenAthens organization ID
openathens_org_id: ${SCITEX_SCHOLAR_OPENATHENS_ORG_ID:-null}

# OpenAthens IDP URL
openathens_idp_url: ${SCITEX_SCHOLAR_OPENATHENS_IDP_URL:-null}

# OpenAthens email
openathens_email: ${SCITEX_SCHOLAR_OPENATHENS_EMAIL:-null}

# OpenAthens username
openathens_username: ${SCITEX_SCHOLAR_OPENATHENS_USERNAME:-null}

# OpenAthens password
openathens_password: ${SCITEX_SCHOLAR_OPENATHENS_PASSWORD:-null}

# OpenAthens institution name
openathens_institution_name: ${SCITEX_SCHOLAR_OPENATHENS_INSTITUTION_NAME:-null}

# ============================================================================
# SEARCH CONFIGURATION
# ============================================================================

# Default sources to search
default_search_sources:
  - pubmed
  - semantic_scholar
  - google_scholar
  - crossref
  - arxiv

# Default number of search results
default_search_limit: 20

# ============================================================================
# PDF MANAGEMENT
# ============================================================================

# Directory for storing downloaded PDFs
pdf_dir: ${SCITEX_SCHOLAR_PDF_DIR:-"~/.scitex/scholar/pdfs"}

# Enable PDF text extraction features
enable_pdf_extraction: true

# ============================================================================
# PERFORMANCE SETTINGS
# ============================================================================

# Maximum number of parallel API requests
max_parallel_requests: 3

# Request timeout in seconds
request_timeout: 30

# Size of LRU cache for journal lookups
cache_size: 1000

# Google Scholar timeout in seconds
google_scholar_timeout: ${SCITEX_SCHOLAR_GOOGLE_SCHOLAR_TIMEOUT:-10}

# ============================================================================
# ADVANCED SETTINGS
# ============================================================================

# SSL certificate verification
verify_ssl: true

# Debug mode
debug_mode: ${SCITEX_SCHOLAR_DEBUG_MODE:-false}

# User agent string for API requests
user_agent: "SciTeX-Scholar/1.0"

# ============================================================================
# LEAN LIBRARY BROWSER EXTENSION
# ============================================================================

# Enable Lean Library browser extension support
use_lean_library: ${SCITEX_SCHOLAR_USE_LEAN_LIBRARY:-true}

# Browser profile path
lean_library_browser_profile: ${SCITEX_SCHOLAR_LEAN_LIBRARY_BROWSER_PROFILE:-null}

# ============================================================================
# INSTITUTIONAL ACCESS
# ============================================================================

# OpenURL resolver for institutional access
openurl_resolver: ${SCITEX_SCHOLAR_OPENURL_RESOLVER_URL:-"https://unimelb.hosted.exlibrisgroup.com/sfxlcl41"}

# ============================================================================
# ZENROWS PROXY CONFIGURATION
# ============================================================================

# ZenRows API key for web scraping
zenrows_api_key: ${SCITEX_SCHOLAR_ZENROWS_API_KEY:-null}

# ZenRows proxy credentials
zenrows_proxy_username: ${SCITEX_SCHOLAR_ZENROWS_PROXY_USERNAME:-null}
zenrows_proxy_password: ${SCITEX_SCHOLAR_ZENROWS_PROXY_PASSWORD:-null}

# ZenRows proxy server settings
zenrows_proxy_domain: ${SCITEX_SCHOLAR_ZENROWS_PROXY_DOMAIN:-"superproxy.zenrows.com"}
zenrows_proxy_port: ${SCITEX_SCHOLAR_ZENROWS_PROXY_PORT:-"1337"}

# ============================================================================
# ZOTERO INTEGRATION
# ============================================================================

# Zotero library ID
zotero_library_id: ${SCITEX_SCHOLAR_ZOTERO_LIBRARY_ID:-null}

# Zotero API key
zotero_api_key: ${SCITEX_SCHOLAR_ZOTERO_API_KEY:-null}

# Library type: "user" or "group"
zotero_library_type: ${SCITEX_SCHOLAR_ZOTERO_LIBRARY_TYPE:-"user"}

# ============================================================================
# 2CAPTCHA INTEGRATION
# ============================================================================

# 2Captcha API key for solving CAPTCHAs
twocaptcha_api_key: ${SCITEX_SCHOLAR_2CAPTCHA_API_KEY:-null}

# Enable automatic CAPTCHA solving
enable_captcha_solving: ${SCITEX_SCHOLAR_ENABLE_CAPTCHA_SOLVING:-true}

# EOF