# Timestamp: "2025-09-30 20:15:03 (ywatanabe)"
# File: ./src/scitex/scholar/config/default.yaml

# ----------------------------------------
# feature
# ----------------------------------------
scholar_dir: ${SCITEX_DIR:-"~/.scitex"}
project: ${SCITEX_SCHOLAR_PROJECT:-"MASTER"}
debug_mode: ${SCITEX_SCHOLAR_DEBUG_MODE:-false}
enable_auto_enrich: ${SCITEX_SCHOLAR_AUTO_ENRICH:-true}
enable_auto_download: ${SCITEX_SCHOLAR_AUTO_DOWNLOAD:-false}

# ----------------------------------------
# Search Engines
# ----------------------------------------
engines:
  - URL
  - CrossRefLocal
  - Semantic_Scholar
  - CrossRef
  - OpenAlex
  - PubMed
  - arXiv

default_search_limit: 20
max_workers: 4
verify_ssl: true

# ----------------------------------------
# cache
# ----------------------------------------
use_cache_search: true
use_cache_url_finder: true
use_cache_pdf_downloader: true


# ----------------------------------------
# api
# ----------------------------------------
semantic_scholar_api_key: ${SCITEX_SCHOLAR_SEMANTIC_SCHOLAR_API_KEY:-null}
crossref_api_key: ${SCITEX_SCHOLAR_CROSSREF_API_KEY:-null}
pubmed_api_key: ${SCITEX_SCHOLAR_PUBMED_API_KEY:-null}
twocaptcha_api_key: ${SCITEX_SCHOLAR_2CAPTCHA_API_KEY:-null}

# ----------------------------------------
# auth:
# ----------------------------------------
# Search Engine
pubmed_email: ${SCITEX_SCHOLAR_PUBMED_EMAIL:-null}
crossref_email: ${SCITEX_SCHOLAR_CROSSREF_EMAIL:-null}
# Auth
openathens_enabled: ${SCITEX_SCHOLAR_OPENATHENS_ENABLED:-true}
openathens_email: ${SCITEX_SCHOLAR_OPENATHENS_EMAIL:-null}
ezproxy_email: ${SCITEX_SCHOLAR_EZPROXY_EMAIL:-null}
shibboleth_email: ${SCITEX_SCHOLAR_SHIBBOLETH_EMAIL:-null}
openurl_resolver_url: ${SCITEX_SCHOLAR_OPENURL_RESOLVER_URL:-null}
sso_username: ${SCITEX_SCHOLAR_SSO_USERNAME:-null}
sso_password: ${SCITEX_SCHOLAR_SSO_PASSWORD:-null}

# Notification settings
notification_email: ${UNIMELB_EMAIL:-null}
notification_from_email: ${SCITEX_EMAIL_AGENT:-"agent@scitex.ai"}

# Screenshot settings
capture_screenshots: ${SCITEX_SCHOLAR_CAPTURE_SCREENSHOTS:-false}

# ----------------------------------------
# browser:
# ----------------------------------------
chrome_profile_name: ${SCITEX_SCHOLAR_CHROME_PROFILE_NAME:-null}

# ----------------------------------------
# URL Finder
# ----------------------------------------

# DOI prefix to publisher domain mapping
doi_to_domain:
  "10.1038":
    - "nature.com"
    - "springernature.com"
  "10.1016":
    - "sciencedirect.com"
    - "elsevier.com"
  "10.1002":
    - "wiley.com"
    - "onlinelibrary.wiley.com"
  "10.1007":
    - "springer.com"
    - "link.springer.com"
  "10.1126":
    - "science.org"
    - "sciencemag.org"
  "10.1021":
    - "acs.org"
    - "pubs.acs.org"
  "10.1111":
    - "wiley.com"
    - "onlinelibrary.wiley.com"
  "10.1080":
    - "tandfonline.com"
  "10.1177":
    - "sagepub.com"
    - "journals.sagepub.com"
  "10.1093":
    - "oup.com"
    - "academic.oup.com"
  "10.1109":
    - "ieee.org"
    - "ieeexplore.ieee.org"
  "10.1371":
    - "plos.org"
    - "journals.plos.org"
  "10.1073":
    - "pnas.org"
  "10.1136":
    - "bmj.com"
  "10.3389":
    - "frontiersin.org"
  "10.3390":
    - "mdpi.com"

# Available from patterns - high priority for OpenURL resolvers
openurl_available_from_patterns:
  # University of Melbourne specific patterns (based on screenshot)
  # Put these first since they are most specific to your use case
  - "Available from American Association for the Advancement of Science"
  - "Available from JSTOR Archival Journals and Primary Sources Collection"
  - "Available from JSTOR Health & General Sciences"
  - "Available from PubMed Central"
  - "Available from American Physiological Society Paid"

  # Publisher-specific patterns (most reliable)
  - "Available from Nature"
  - "Available from Nature Publishing Group"
  - "Available from ScienceDirect"
  - "Available from Elsevier"
  - "Available from Wiley"
  - "Available from Wiley Online Library"
  - "Available from Springer"
  - "Available from SpringerLink"
  - "Available from Taylor & Francis"
  - "Available from SAGE"
  - "Available from SAGE Publications"
  - "Available from Oxford"
  - "Available from Oxford Academic"
  - "Available from IEEE"
  - "Available from IEEE Xplore"
  - "Available from PLOS"
  - "Available from PLOS ONE"
  - "Available from BMJ"
  - "Available from Frontiers"
  - "Available from MDPI"
  - "Available from American Chemical Society"
  - "Available from ACS"
  - "Available from ACS Publications"
  - "Available from PNAS"
  - "Available from Science"
  - "Available from AAAS"

# available_from_patterns:
#   # Generic available patterns
#   - "Full text available from"
#   - "View full text at"
#   - "Access full text from"
#   - "Get full text from"

# Resolver link selectors in priority order
structure_selectors:
  # University of Melbourne specific (based on screenshots)
  - 'tr:has-text("Available from") a:has-text("GO")'
  - 'td a[href*="javascript:openSFXMenuLink"]:has-text("GO")'
  - 'a[title="Navigate to target in new window"]'

  # SFX (ExLibris) - used by many universities
  - "div#fulltext a"
  - "div.sfx-fulltext a"
  - "div.results-title > a"
  - "td.object-cell a"
  - ".getFullTxt a"
  - 'div[id*="fulltext"] a'
  - 'div[class*="fulltext"] a'

  # Primo (ExLibris)
  - "prm-full-view-service-container a"
  - "span.availability-status-available a"

  # Summon (ProQuest)
  - ".summon-fulltext-link"
  - "a.summon-link"

  # EDS (EBSCO)
  - "a.fulltext-link"
  - ".ft-link a"

  # Generic patterns
  - "a.full-text-link"
  - "a.fulltext"
  - "a#full-text-link"
  - ".access-link a"
  - ".available-link a"

text_patterns:
  # Common patterns
  - "View full text"
  - "Full Text from Publisher"
  - "Get full text"
  - "Access full text"
  - "Go to article"
  - "Access article"

  # Generic but reliable
  - "Full Text"
  - "Full text"
  - "Article"
  - "View"
  - "PDF"
  - "Download"
  - "GO"

negative_keywords:
  - "cookie"
  - "policy"
  - "about us"
  - "privacy"
  - "terms"
  - "abstract"
  - "preview"
  - "summary"
  - "citation"
  - "cite this"
  - "request"
  - "interlibrary"
  - "inter library"
  - "loan"


# PDF download selectors for direct link finding
download_selectors:
  # Generic download patterns
  - 'a[data-track-action*="download"]'
  - 'button[data-track-action*="download"]'
  - 'a:has-text("Download PDF")'
  - 'button:has-text("Download PDF")'
  - 'a[download][href*="pdf"]'
  - '.pdf-download-btn'
  - 'a[href*="/pdf/"]'
  - 'a[href*="/doi/pdf/"]'
  - 'a[href*="type=printable"]'

  # Publisher-specific selectors
  # ScienceDirect (Elsevier)
  - 'a.PdfLink'
  - 'a.article-tools-pdf-link'

  # Wiley Online Library
  - 'a#article-pdf-link'
  - 'a.pdf-download'

  # SpringerLink
  - 'a[data-track-action="download pdf"]'
  - 'a.c-pdf-download__link'

  # Oxford Academic
  - 'a.al-link.pdf-link'

dropdown_selectors:
  - 'button:has-text("Download")'
  - '.dropdown-toggle:has-text("Download")'
  - '[data-toggle="dropdown"]:has-text("Download")'
  - ".download-dropdown"
  - 'button[aria-label*="Download"]'

supplementary_selectors:
  - 'a[href*="supplementary"]'
  - 'a[href*="supplement"]'
  - 'a[href*="additional"]'
  - 'a[href*="supporting"]'
  - 'a[href*="SI"]'
  - 'a[href*="ESM"]'

pdf_view_selectors:
  - 'a:has-text("View PDF")'
  - 'a:has-text("PDF")'
  - "a.pdf-link"
  - 'a[href*="/pdf/"]'
  - 'button:has-text("PDF")'
  - 'a#ViewPDF'
  - 'div#accessbar a'

# Deny patterns for filtering out unwanted elements
deny_selectors:
  # Navigation and UI elements
  - 'aside *'
  - '.sidebar *'
  - '.navigation *'
  - '.footer *'
  - '.header *'
  # Recommendation sections
  - '.recommended *'
  - '.related-articles *'
  - '.you-may-also-like *'
  # Social and sharing
  - '.social-share *'
  - '.share-buttons *'
  # Issue/Volume downloads (not single article)
  - 'a:has-text("Download Issue")'
  - 'a:has-text("Download Volume")'
  - 'a:has-text("Full Issue")'

deny_classes:
  - "recommended"
  - "sidebar"
  - "footer-content"
  - "social-share"
  - "issue-download"
  - "volume-download"

deny_text_patterns:
  - "Download Issue"
  - "Download Volume"
  - "Full Issue"
  - "Complete Issue"
  - "Entire Issue"
  - "Subscribe"
  - "Sign up"

# EOF