name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy
    
    - name: Run black (check only)
      run: |
        black --check --diff src/scitex tests/
    
    - name: Run isort (check only)
      run: |
        isort --check-only --diff src/scitex tests/
    
    - name: Run flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 src/scitex tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 src/scitex tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run mypy
      continue-on-error: true  # MyPy might have many errors initially
      run: |
        mypy src/scitex --ignore-missing-imports --no-strict-optional